desc 'Run all tests; pattern is not required.'
task :test, [:pattern] do |t, args|
  # register tests to execute (via Minitest#autorun) at process exit
  pattern = args.fetch(:pattern, './tests/**/test_*.rb')
  file_paths = Dir.glob(pattern)
  puts "Files: #{file_paths.sort.join(' ')}"
  file_paths.each { |file| require_relative(file) }
end

task default: :test
